default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: frederick-bouldering

test:
  <<: *default
  database: frederick-bouldering-test

production:
  <<: *default
  database: frederick-bouldering-production
